import { m } from "framer-motion";

{ /* Internship Projects Words Highlights */}
const internship_keywords = [
    "dense retrieval",
    "accuracy",
    "relevancy",
    "new search method",
    "Hypothetical Document Embeddings (HyDE)",
    "Meta's Llama 3",
    "large language model",
    "(LLM)",
    "enhanced the accuracy",
    "enhance",
    "information retrieval",
    "advanced search algorithm",
    "search query",
    "synthetic doctor's note",
    "identifying",
    "irrelevant",
    "relevant",
    "precise",
    "matches",
    "wider range",
    "goal",
    "migrate",
    "Go services",
    "Kubernetes",
    "Scalability",
    "reduce Infrastructure costs",
    "Improved deployment efficiency",
    "knowledge gained",
    "impact of the migration",
    "enabled",
    "led",
    "Tilt",
    "Minikube",
    "Docker",
    "configurations",
    "containerizing services",
    "Local Kubernetes development environment",
    "hands-on experience",
    "reduced downtime",
    "optimized resource allocation",
    "system performance",
    "presented my work and insights",
    "60+ software engineers",
    "visibility",
    "service metrics",
    "latency",
    "request volume",
    "error rates",
    "service level objectives (SLOs)",
    "Go-based diagnostic tool",
    "Datadog API",
    "performance metrics",
    "search functionality",
    "critical insights",
    "hit counts",
    "analyze trends",
    "recommended SLOs",
    "optimize application performance",
    "service observability",
    "centralized tool",
    "monitoring key performance metrics",
    "identify bottlenecks",
    "optimize SLOs",
    "system reliability",
    "audience of",
    "streamlined",
    "performance monitoring",
    "proactive",
    "troubleshooting",
    "performance jobs", 
    "time-consuming", 
    "manually check", 
    "parameters", 
    "wait for results", 
    "efficiency", 
    "productivity",
    "web-based performance job execution tool",
    "Python",
    "CGI Programming",
    "Shell Scripting",
    "interactive UI",
    "frequently used parameters",
    "enabling users",
    "interactive interface",
    "select options",
    "menu-like system",
    "automatically generating and executing command-line jobs",
    "email notification feature",
    "update users on job status and results",
    "enabling them to focus on other tasks",
    "waiting for completion",
    "existing regression report",
    "outdated",
    "lacked key functionalities",
    "data analysis",
    "interactive",
    "user-friendly report",
    "efficiently processing summary files",
    "new report generation system",
    "JavaScript",
    "HTML",
    "CSS",
    "features",
    "sorting",
    "tooltips",
    "customizable reports",
    "user-defined",
    "Improved report usability and efficiency",
    "quickly analyze regression results",
    "first N rows, past N days, and branch-specific runs,",
    "streamlining decision-making and debugging.",
    "improved"
]

export default internship_keywords;