import { m } from "framer-motion";

// Internship Issues/Problems
const internship_issues = [
    "produced a significant number of irrelevant results",
    "required better visibility into key service metrics",
    "Running performance jobs was time-consuming",
    "manually check parameters and wait for results",
    "limiting efficiency and productivity",
    "existing regression report was outdated",
    "lacked key functionalities for data analysis"
]

// Internship Technical Terms/Tools
const internship_tech_keywords = [
    "dense retrieval",
    "Hypothetical Document Embeddings (HyDE)",
    "Meta's Llama 3",
    "Large Language Model (LLM)",
    "synthetic doctor's note",
    "search query for dense retrieval",
    "latency",
    "request volume",
    "error rates",
    "service level objectives (SLOs)",
    "Go-based diagnostic tool",
    "Datadog API",
    "Go services",
    "performance metrics",
    "search functionality",
    "hit counts",
    "generate recommended SLOs",
    "SLOs",
    "local kubernetes development environment",
    "containerizing services",
    "Kubernetes",
    "system performance",
    "Scalability",
    "Tilt",
    "Minikube",
    "Docker",
    "configurations",
    "Python",
    "CGI Programming",
    "Shell Scripting",
    "web-based performance job execution tool",
    "select frequently used parameters",
    "interactive web-based tool",
    "interactive UI",
    "interactive interface",
    "command-line jobs",
    "email notification feature",
    "report generation system",
    "JavaScript",
    "HTML",
    "CSS",
    "interactive features",
    "sorting (by date, numbers, and alphabetical order)",
    "tooltips",
    "customizable reports",
    "functionality",
    "debugging"
]

// Internship impact or business contribution
const internship_keywords = [
    "improving search results for qualifying candidates",
    "accuracy and relevancy",
    "enhanced the accuracy of identifying potential clinical trial candidates",
    "resulting in more relevant and precise matches",
    "across a wider range of medical topics",
    "ensuring optimal application performance",
    "improved reliability",
    "optimize application performance",
    "improved service observability",
    "centralized tools",
    "quickly identify bottlenecks",
    "optimize SLOs",
    "enhance system reliability",
    "system reliability",
    "presented my work",
    "and insights",
    "audience of 60+ software engineers",
    "streamlined performance monitoring and proactive troubleshooting",
    "improve deployment efficiency",
    "Led the setup",
    "reduce infrastructure costs",
    "enhance",
    "hands-on experience",
    "ensuring seamless deployment",
    "improved deployment efficiency",
    "reduced downtime",
    "optimized resource allocation",
    "better system performance",
    "demonstrating the impact of the migration and knowledge gained",
    "select options from a menu-like system",
    "automatically generating and executing",
    "update users on job status and results",
    "focus on other tasks instead of waiting for completion",
    "better data insights",
    "more interactive and user-friendly report",
    "efficiently processing summary files",
    "enhancing data visualization",
    "Improved report usability and efficiency",
    "quickly analyze regression results",
    "streamlining decision-making"
]

export { internship_issues, internship_keywords, internship_tech_keywords };